### ISSUE TITLE
Reverse/unpredictable order after uploading

### ISSUE THREAD

**Issue by liquid06** [omeka/plugin-Dropbox#19]
I'm adding some books to an Omeka site and I'm using dropbox to handle uploading the large numbers of image files to attach to items. In our setup for this collection one item could have 400-700 files attached to it. For adding the files with dropbox, this seemed to work best in batches of 100 at a time because of the php settings on our server. 

Before uploading, the files seem to be in the correct order. They have a sequence number as part of the filename:
![before-loading](https://user-images.githubusercontent.com/460005/28072275-62e0d770-6607-11e7-9b9d-95fef4ae52d4.png)

But after they've been attached, they're in the reverse order:
![why](https://user-images.githubusercontent.com/460005/28072319-75dbc0ba-6607-11e7-8fb0-e7c68c7b8b54.png)

I encountered one case where part of the batch was attached to the beginning of the list of existing files and the other part of the batch was added to the end. (That only happened once, most other times the batch was added to the end of the list just with the order reversed.)

One other interesting case I ran into was having only some of the batch in reverse order. Having just uploaded a batch including files numbered 200-299: the whole batch was appended to the end of the list of existing files, and the order following file `199` was like this: `211, 210, 209 ... 201, 200` followed by the rest of the files in the opposite order `212, 213, 214, 215 ... 298, 299`

**Comment by zerocrates** [comment]
This was fixed in the core in version 3.1.2, for the Dropbox case and pretty much any other with this "large number of files" situation. Existing items with this problem where the file order hasn't been manually changed since upload may have their order fixed by the update also.
